Docker, everything but OIDC. OIDC fails due to the fact that NginX is not forwarding the Host headers, and so .netcore still 'thinks' it is running on :4213 (Google):
System.Security.Authentication.AuthenticationException: Results: {
  "error": "redirect_uri_mismatch",
  "error_description": "Bad Request"
}

RedirectUri: http://localhost:4213/id/signin-google

(Should be https://localhost/id/signin-google, which should be "truth,"
according to the Request document.)

https://github.com/aspnet/Security/issues/1857#issuecomment-423220328
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2#configure-nginx

Comb this and fix. Some of the groundwork has already been laid here.

Signing off, blah bleary 3 am